# Generated by Django 6.1 on 2026-08-18 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Leave blank to broadcast across all departments.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'Everyone'), ('TEACHERS', 'Faculty / Teachers Only'), ('STUDENTS', 'Students Only'), ('STAFF', 'Admin / Staff Only')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GENERAL', 'General Notice'), ('VERIFICATION', 'Verification & Registration'), ('SECURITY', 'Security & Profile Update'), ('ATTENDANCE', 'Attendance Alert'), ('URGENT', 'Urgent Announcement')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='If blank, broadcasted to the selected Target Audience.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
