# Generated by Django 6.1 on 2026-08-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timetable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='course',
            name='total_planned_classes',
            field=models.PositiveIntegerField(default=40, help_text='Total number of sessions required to complete the curriculum'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_extra_class',
            field=models.BooleanField(default=False, help_text='Designates this session as an extra/makeup class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='specific_date',
            field=models.DateField(blank=True, help_text='Required if scheduling an extra class on a specific date', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
