# Generated by Django 6.1 on 2026-08-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_timetable_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
