# Generated by Django 6.1 on 2026-08-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_count',
            field=models.PositiveIntegerField(default=0, help_text='Tracks number of times user changed password (Maximum 2 allowed)'),
        ),
    ]
